services:
  casaos:
    container_name: casaos
    build:
      context: .
      dockerfile: dockerfile
    privileged: true # 必须: 在 docker 容器中运行 docker (D IN D), 特权模式是必要的
    volumes:
      - ./data:/DATA # 可选: 将 DATA 目录映射到外部, 以便持久化
      # - ./docker:/var/lib/docker # 可选: 将 docker 数据映射到外部, 以便持久化, todo: 似乎有问题
      # - ./casaos-db:/var/lib/casaos/db               # 可选: 将 casaos 数据目录映射到外部, 以便持久化, todo: 似乎有问题
    # network_mode: host
    ports:
      - "9080:80"
      - "9081:81"
      - "9082:82"
      - "9083:83"
      - "9084:84"
      - "9085:85"
    restart: always
